export const GET_USERS_FETCH = 'GET_USERS_FETCH';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_PHOTOS_FETCH = 'GET_PHOTOS_FETCH';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';